### PR TITLE
Fix segfault caused by misspelled(?) font name.

### PR DESCRIPTION
**Pull request by seanlynch**
Also fixes an error where GLM refuses to compile due to use of an experimental feature.

I'm still getting a gray screen on Arch Linux with an Intel GPU, though. Looking into that.

### CODE REVIEW

**Comment by azsn** [comment]
The font is actually 'ttc' (TrueType Collection) on my Arch Linux install. The better solution would be to make it not crash on missing font. I'm also getting a gray screen after upgrading to GLM 0.9.9, however it works on 0.9.8.5. I'll see if I can figure out the problem; it'll give me an excuse to work on cleaning up this project, as I've been meaning to do that for a long time now. Thanks!

**Comment by santaclose** [comment]
hello, any news on the gray screen issue?  I cloned the repository and installed the fonts but I'm still not able to see any text. Thanks in advance.

**Comment by azsn** [comment]
@santaclose No, sorry, I haven't looked into it yet :(

**Comment by santaclose** [comment]
I fixed the problem by changing the four mat4 initializations in the demo.cpp file. It seems that they removed default initializations in glm 0.9.9 so now to create an identity matrix we must use mat4(1.0) instead of mat4()

**Comment by azsn** [comment]
@santaclose Oh great! Thank you. Unfortunately I'm not able to easily run or test this program at all right now. Hopefully I can try that out on a new version of glm at some point soon, though, and commit the fix.

**Comment by azsn** [comment]
@santaclose Took me long enough, but I updated the demo and it's compiling and working on my Mac now. Fixed the `glm::mat4()` bug, thanks!

I'm going to close this PR because the font name change doesn't apply anymore (I've included LiberationSans in the repo to make running this easier). I added the `GLM_ENABLE_EXPERIMENTAL` though because it's needed for `#include <glm/gtx/transform.hpp>`, although strangely I don't get any errors or warnings for using it without experimental enabled.

**Pull request closed without merging**
